services:
  - type: web
    name: cobalt-telegram-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: PYTHON_VERSION        # 👈 YEH ADD KARO
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: cobalt-bot-db
          property: connectionString

databases:
  - name: cobalt-bot-db
    databaseName: cobalt_bot
    user: cobalt_bot_user
    plan: free
